# Exported from Render on 2025-06-16T01:02:46Z
services:
- type: web
  name: conselhotutelarmoc
  runtime: static
  repo: https://github.com/AdaCSilva/trabeng
  envVars:
  - key: REACT_APP_API_URL
    sync: false
  - key: PORT
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_HOST
    sync: false
  - key: .env
    sync: false
  buildCommand: npm run build
  staticPublishPath: build
  routes:
  - type: rewrite
    source: /*
    destination: /index.html
  autoDeployTrigger: commit
version: "1"
